### ISSUE TITLE
Please merge Ramarren's pull requests

### ISSUE THREAD

**Issue by enceos** [snjo/Firespitter#103]
Ramarren has written in many crucial fixes which resolve many problems with Regolith and MKS/Karbonite. If these fixes get added officially, Firespitter will open a new horizon of possibilities for modders.

Thank you Snjo!

**Comment by snjo** [comment]
I don't know what fixes you are talking about.

**Comment by enceos** [comment]
well, did you look into the pull requests? they have comments

**Comment by snjo** [comment]
Well, I already merged that pull request some time ago
