### ISSUE TITLE
For KSP 1.0

### ISSUE THREAD

**Issue by Bear67** [snjo/Firespitter#105]
No version info on the DLL itself.
![screenshot_3](https://cloud.githubusercontent.com/assets/5138687/7430476/9aa8d442-efd9-11e4-9134-8114b312181e.jpg)

**Comment by InsanePlumber** [comment]
https://github.com/snjo/Firespitter/tree/master/For%20release/Firespitter/Plugins

**Comment by snjo** [comment]
I get the version number when i download from the repository. Must be a local issue.

**Comment by Bear67** [comment]
Yeah, i figured it out. I was right-clicking - save as.. for just the dll and was only getting a 44K dll, but when I D/L as a Zip I'm getting the 256K version that has all the Version info.
![screenshot_4](https://cloud.githubusercontent.com/assets/5138687/7462356/660ea2e4-f276-11e4-9fb5-60530c6f5454.jpg)
