### ISSUE TITLE
AVC Version Wrong

### ISSUE THREAD

**Issue by robert-cassidy** [snjo/Firespitter#107]
The latest 7.1 version includes the following .version info:

{
  "NAME": "Firespitter",
  "URL": "https://raw.githubusercontent.com/snjo/Firespitter/master/For%20release/Firespitter/Firespitter.version",
  "VERSION": {
    "MAJOR": 7,
    "MINOR": 0,
	"PATCH": 0
  },
  "KSP_VERSION": {
    "MAJOR": 0,
    "MINOR": 90,
    "PATCH": 0
  }
}

Should be 7.1 and 1.0 - probably add KSP_VERSION_MIN and KSP_VERSION_MAX

**Comment by BobPalmer** [comment]
I just looked in both the ZIP and the source file from the release page - all of these are up to date.  Are you sure you didn't forget to overwrite something?  Or did you get the ZIP from somewhere else?

Closing as this looks to not be an issue based on source files.
