### ISSUE TITLE
KSP 1.0.2 FS wings don't create lift

### ISSUE THREAD

**Issue by steampilot** [snjo/Firespitter#110]
Tested the new release of Firespiter for KSP version1.0.2 by buidling a Byplane.
The wings won't create lift. Debuging with the cheat menu confirms. Building in VAB shows no lift vector change when moving the wings around.

Since KSP 1.0.0 introduce its own Airodynamics model i am not sure if the FAR module inside of the wings part.cfg ist still valid. I tried to tinker with it, I was able to get the wings to produce lift by removing the FAR module. But i wasnt able to make them steady.

**Comment by snjo** [comment]
I flew a biplane just fine in 1.0. Did you try flying it, or are you referring to the lift display in the SPH?

**Comment by ultrasquid** [comment]
i used FS biplane wings and the plane flew fine for me too, but the lift
does not display either with the center-of-lift indicator in the SPH or
with the new aerodynamic spike display in-flight.

On Sat, May 9, 2015 at 11:32 AM, Andreas Aakvik Gogstad <
notifications@github.com> wrote:

> I flew a biplane just fine in 1.0. Did you try flying it, or are you
> referring to the lift display in the SPH?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/snjo/Firespitter/issues/110#issuecomment-100528002>.
>



-- 
-- 
Jason Pagura
zimbach at gmail dot com

**Comment by steampilot** [comment]
I did test fly it of course. And it never liftet off the ground. Thats why i started to investigate.

**Comment by steampilot** [comment]
Closing outdated issue my self.
