### ISSUE TITLE
FSfuelSwitch don't add fuel costs

### ISSUE THREAD

**Issue by LeLeon** [snjo/Firespitter#168]
as above said, no fuel costs are added in editor scene, only the normal "costs = " entry is count. means switching to other ressources like Xenon leads to a high negative value (and results in a cheat, when going to flight scene). 
I tried to calculate the fuel costs and set it as tankCost. Works, until i use tweakscale. NOW fuel costs will be calculated and the tankcost will be here converted to drycost.

[Tweakscale thread](http://forum.kerbalspaceprogram.com/index.php?/topic/99956-wip-tweakscale-development-thread/&do=findComment&comment=2847841)

Edit: Seems that also tankMass will be ignored. Sometimes i see while switch through the tank setups the mass+tankmass for a millisecond, but the mass stay at least.

Thats what i use for a tank

> 	MODULE
> 	{
> 	    name = FSfuelSwitch
> 		moduleID = 0
> 		resourceNames = Structural;MonoPropellant,ElectricCharge;ElectricCharge
> 		resourceAmounts = Structural;200,250;650
> 		tankCost = 10;490;650
> 		tankMass = 0.125;0.16;0.135
> 		basePartMass = 0.125
> 		displayCurrentTankCost = true
> 		hasGUI = true
> 		availableInFlight = false
> 		availableInEditor = true
> 		showInfo = true
> 	}

Tried it with only mod+firespitter, same result.

**Comment by Iskie** [comment]
Going to add that I confirm this, when switching fuel the cost of the part is locked. Switching a 3.75m part to xenon and removing the fuel gives a part worth nearly -300,000 kerbucks. Only mod affecting the part (and only non-stock module whatsoever) is Firespitter's fuel switching.

Also confirmed that when launched in career, player will gain that money, and when recovered it will be lost, so is not sanity-checked by KSP at any point.

**Comment by BobPalmer** [comment]
This is likely an issue with that config, given that I use the heck out of variable cost tanks all the time....
