### ISSUE TITLE
Sound - you're doing it wrong.

### ISSUE THREAD

**Issue by smoketh** [snjo/Firespitter#179]
(in FSEngineSounds.cs)

`group.audio = gameObject.AddComponent<AudioSource>();

                group.audio.volume = GameSettings.SHIP_VOLUME;

                //group.audio.rolloffMode = AudioRolloffMode.Logarithmic;            

                group.audio.rolloffMode = AudioRolloffMode.Linear;

                group.audio.dopplerLevel = 0f;

                group.audio.panStereo = 1f;

                group.audio.clip = GameDatabase.Instance.GetAudioClip(name);

                group.audio.loop = loop;

                group.audio.playOnAwake = false;
`
What is this? why are you panning audio all the way to the right and deliberately not setting it to 3d? Unity3d (in 5.0) switched audiosource functions and added default sound to 2d.
For the love of god - read documentation.
Here's fixed version - i'm not gonna bother do pull even, since it's only 1 float change and one line added
`group.audio = gameObject.AddComponent<AudioSource>();

                group.audio.volume = GameSettings.SHIP_VOLUME;

                //group.audio.rolloffMode = AudioRolloffMode.Logarithmic;            

                group.audio.rolloffMode = AudioRolloffMode.Linear;

                group.audio.dopplerLevel = 1f;

                group.audio.panStereo = 0.5f;

                group.audio.clip = GameDatabase.Instance.GetAudioClip(name);

                group.audio.loop = loop;

                group.audio.playOnAwake = false;

                group.audio.spatialBlend = 1f;
`

**Comment by BobPalmer** [comment]
Wow.  I mean, thanks for the bit of code, but there was zero reason to be a complete asshole about it.
