### ISSUE TITLE
1.4.1 crashes even with 1.4.0 .dll's

### ISSUE THREAD

**Issue by Alfrys** [snjo/Firespitter#191]
Tried few things and all led to firespitter core .dll's. Game crashes just after initial loading screen before entering main menu. Game doesn't even give crash log so can't help you there.

Tested with 1.4.1.2089 64bit launcher and win10.

**Comment by BobPalmer** [comment]
I've been using the 1.4 DLLs for a bit without issue, need more details.

**Comment by Alfrys** [comment]
sorry I think just this ksp update is not friendly with MSI Afterburner and crashes game at that point at random game launches
