### ISSUE TITLE
Legacy bi-plane parts still in release

### ISSUE THREAD

**Issue by aldobro19** [snjo/Firespitter#224]
Seems this has fallen through the cracks of time... 🙃

https://forum.kerbalspaceprogram.com/index.php?/topic/22583-firespitter-propeller-plane-and-helicopter-parts-v71-may-5th-for-ksp-10/page/109/&tab=comments#comment-2915142

**Comment by Lisias** [comment]
As it should be.

The legacy parts are there to keep older crafts and savegames loadable.

Squad does it too, if you have crafts using liquidEngine24-77 are still loadable on KSP 1.10, besides there part being now legacy and new crafts are made using liquidEngine24-77_v2 .

These parts should stay where they are.

**Comment by aldobro19** [comment]
Let's be pragmatic about this, it was rebuilt over 4 years ago for 1.1. Is anyone _really_ playing 1.0 or below? Is anyone loading crafts from before the aerodynamics overhaul?

I'm only bringing this up because when I tried to remove them from my own install, Firespitter borked and wouldn't load. Possible user error, but it went away when I replaced the folder. Loading KSP for 10 minutes just to see if I deleted the parts correctly is a bit of a waste of time, and I'd rather just leave them, but they do add clutter. My two cents.

**Comment by BobPalmer** [comment]
tbh I will probably just move the legacy parts to an optional subfolder in the zip

**Comment by Lisias** [comment]
> Let's be pragmatic about this, it was rebuilt over 4 years ago for 1.1. Is anyone _really_ playing 1.0 or below? Is anyone loading crafts from before the aerodynamics overhaul?

Yes, we are. And building custom parts with the assets, being in use until nowadays.




> Let's be pragmatic about this, it was rebuilt over 4 years ago for 1.1. Is anyone _really_ playing 1.0 or below? Is anyone loading crafts from before the aerodynamics overhaul?
> 
> I'm only bringing this up because when I tried to remove them from my own install, Firespitter borked and wouldn't load. Possible user error, but it went away when I replaced the folder. Loading KSP for 10 minutes just to see if I deleted the parts correctly is a bit of a waste of time, and I'd rather just leave them, but they do add clutter. My two cents.
> 
> Besides, Squad has a different standard because their parts are in 100% of savegames; using Firespitter's parts or not is a choice. No mod user should expect their mods to be at the same standard as a professionally released software; it is just voluntary after all. You should not worry about a 4-year-old Firespitter part breaking saves; I personally wouldn't expect to load a modded craft or save from over 4 years ago, with all the changes to the base game, without problems.

Your use case is only your use case. Don't project your own expectations on everybody else.

The world is way bigger than you.


> Besides, Squad has a different standard because their parts are in 100% of savegames; using Firespitter's parts or not is a choice. No mod user should expect their mods to be at the same standard as a professionally released software; it is just voluntary after all. You should not worry about a 4-year-old Firespitter part breaking saves; I personally wouldn't expect to load a modded craft or save from over 4 years ago, with all the changes to the base game, without problems.

Of couse using Firespitter parts are a choice!! Otherwise they would not be needed at first place!

The very reason of writting mods it to gave users **MORE CHOICES**. What do you think made KSP such a huge success in the past? The restricted, monothematic palette of parts?

You are completely out of phase about what's a Mod Scene is at all!

**Comment by Lisias** [comment]
> No mod user should expect their mods to be at the same standard as a professionally released software; it is just voluntary after all.

On the other hand, yes. It's voluntary work, and you are right about it.

However, being voluntary or not, breaking user's toys gives you a bad reputation - being it fair or unfair. The equilibrium between removing features to save work and and handling heat due breaking user's savegames is fragile to say the least.

Say someone offers you some help on doing the gardening, and while doing the job destroys your award-winning rose bush. It's his fault? OF COURSE IT IS. He is not liable, but it's still his fault. And, in a way or another, you will never again allow him on your garden.

Software is the same thing. If you make a living doing gardens, do your best to avoid destroying other people's rose bush even when doing it for free.

**Comment by aldobro19** [comment]
Maybe I have a different viewpoint as the end-user, but a comfortable approach in the middle seems to be what the author of Tantares does; he will leave a depreciated part in for the next release as not to break saves, but only for the next release. I don't think anyone has cried about that, and I certainly don't think people have stopped considering Tantares as one of the premier part packs.

Besides, people playing older versions can download the appropriate versions of the mods as archived here or on CKAN. 

My apologies for noticing something that possibly slipped through the cracks and trying to be useful. Instead of being condescending, consider that for the average KSP player, it is much easier to have the authors rid old parts than try to figure out that ModuleManager cached things and refused to load.

**Comment by Lisias** [comment]
> Maybe I have a different viewpoint as the end-user

Sounds like something [CD Projekt RED managers](https://screenrant.com/cyberpunk-2077-update-dlc-why-delay-board-meeting/) would had said. :)


>  but a comfortable approach in the middle seems to be what the author of Tantares does;

The point you fail to get is that we make a living by letting the users have a comfortable approach to the problems.

We earn money (or reputation, or whatever you are seeking in return for the work) by doing their lives easier, not yours.




> he will leave a depreciated part in for the next release as not to break saves, but only for the next release. I don't think anyone has cried about that, and I certainly don't think people have stopped considering Tantares as one of the premier part packs.

That would be a reasonable approach on a Open Source model, where any discontent could fork the project and "fix" it. Tantares is one of these projects, Firespitter is not.

Once the assets are removed from the distribution, there's no way to strictly legally redistribute them again. Not to mention forum rules.

So anyone in need to keep using the assets would just move their business out of the main community, creating parallel communities, weakening  the main stream.

 
> Besides, people playing older versions can download the appropriate versions of the mods as archived here or on CKAN.

But by doing it, the user will be locked on an older version of KSP, mining the Squad's opportunities to sell him a new DLC.

Remember, these guys have to eat. Solutions that mines a sell opportunity are **never** a good solution - someone has to feed these guys so they can work on KSP and keep it running.


> My apologies for noticing something that possibly slipped through the cracks and trying to be useful. Instead of being condescending, 

My apologies to having to teach you how to keep a userbase happy (or the least unhappy possible) so you can keep your business running. You need incoming from 100% of your userbase - if you focus on the niche that prises you, the dissidents will migrate to your competition. You need the money of the 100% of your users, not only from the ones that thinks like you.

Food for thought: Do you know a company called CD Projekt Red? They made a **Hell** of a game, perhaps one of the games of the whole decade. But yet...


> consider that for the average KSP player, it is much easier to have the authors rid old parts than try to figure out that ModuleManager cached things and refused to load (no way to know legacy parts exist without first loading them and seeing them in the tech tree/part list).

Again, this is not about making author's life easier. It's about making **THE USER**'s life easier. You keep failing to grasp this basic principle.

It's up to the author to figure out how Module Manager cache things and do his best to avoid parts being refused to load. or to get out of the way and let someone else do it.

**Comment by snjo** [comment]
I don't think you need to have this debate here.

**Comment by BobPalmer** [comment]
Closing this.  Legacy parts will be hidden but remain in a subfolder (for those wanting to save on RAM), but not in the main toolbox.

**Comment by aldobro19** [comment]
> I don't think you need to have this debate here.

For real, I was scrolling the forum and noticed something that the current maintainer himself had planned. Thanks @snjo and @BobPalmer.

**Comment by Lisias** [comment]
> Closing this. Legacy parts will be hidden but remain in a subfolder (for those wanting to save on RAM), but not in the main toolbox.

How about a secondary ZIP file, and an additional CKAN entry for the deprecated parts?

This way, non interested people would not even had to download the assets, and interested people would just install an additional package on their games...

**Comment by BobPalmer** [comment]
There is already a legacy parts folder in the project, they will be there.  No downloading, and no maintaining another package for CKAN.

**Comment by Lisias** [comment]
Sadly, mr [Al Dobro](https://webcache.googleusercontent.com/search?q=cache:qpCZ70ESPbkJ:https://github.com/aldobro19+&cd=68&hl=en&ct=clnk&gl=br&client=safari) account was deleted.I can't reach him anymore, if someone else has his contact, please advise.
