### ISSUE TITLE
Texture switcher for groups of objects

### ISSUE THREAD

**Issue by snjo** [snjo/Firespitter#41]
Hi Snjo,

Here's a complete copy of a version of FusTek parts that makes rudimentary use of FStextureSwitch:

https://www.dropbox.com/s/obc8z7r2fm...3-for_snjo.zip

With regards to the comma-delimited textures feature request, my situation is as follows:

- I have a number of "Karmony" series parts that use the same base model and common texture set, each differentiated by swapping out a separate, little icon texture assigned to the module_id_symbol object.

- I essentially would like the ability to, whenever the common texture set is changed (to, for instance, KSO style), update the style of the icon sets as well.

Please let me know if I can assist you with additional information / files.

Regards sumghai

**Comment by sumghai** [comment]
I've revised my models and textures so that this feature is no longer required.

Closing.
